=== cosimo265598/distributedprogramming_2/xml_file/Lab1/accounts.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"> 

<xsd:element name="MultiAccountBank">
	<xsd:complexType>
		<xsd:sequence> 
				 <xsd:element name="account" minOccurs="1" maxOccurs="unbounded">
				  <xsd:complexType> 
				   <xsd:sequence> 
				    <xsd:element name="holder" type="HolderType" minOccurs="1" maxOccurs="unbounded"/> 
				    <xsd:element name="yearOperations" type="YearOperationsType" minOccurs="0" maxOccurs="unbounded"/> 
				   </xsd:sequence> 
				   <xsd:attribute name="number" type="xsd:positiveInteger" use="required"/>
				  </xsd:complexType>
				  	
				  	<xsd:unique name="uniqueID_more">
						<xsd:selector xpath="holder" />
						<xsd:field xpath="@fiscalID" />
					</xsd:unique> 
				  	<xsd:unique name="uniqueyear">
						<xsd:selector xpath="yearOperations" />
						<xsd:field xpath="@year" />
					</xsd:unique>
				 </xsd:element>				 
	 </xsd:sequence>
	</xsd:complexType>
				 <xsd:unique name="uniquenumber">
						<xsd:selector xpath="account" />
						<xsd:field xpath="@number" />
				</xsd:unique>
				
</xsd:element>

 <xsd:complexType name="HolderType">
  <xsd:attribute name="name" type="xsd:string" use="required"/>
  <xsd:attribute name="address" type="xsd:string" use="required"/>
  <xsd:attribute name="fiscalID" type="codfiscalIDtype" use="required"/>
 </xsd:complexType>

 <xsd:complexType name="YearOperationsType">
  <xsd:sequence> 
   <xsd:element name="operation" type="OperationType" minOccurs="1" maxOccurs="unbounded"/> 
  </xsd:sequence> 
  <xsd:attribute name="year" type="xsd:positiveInteger" use="required"/>
 </xsd:complexType>
 
 <xsd:simpleType name="Currency">
  <xsd:restriction base="xsd:decimal"> 
   <xsd:fractionDigits value="2"/> 
  </xsd:restriction> 
 </xsd:simpleType>
 
 <xsd:simpleType name="codfiscalIDtype">
  <xsd:restriction base="xsd:string"> 
   <xsd:length value="16"/>
   <xsd:pattern value="[a-zA-Z0-9]*"/>
  </xsd:restriction> 
 </xsd:simpleType>
 
 <xsd:complexType name="OperationType">
  <xsd:all>
    <xsd:element name="description" type="xsd:string" minOccurs="0"/>
  </xsd:all>
  <xsd:attribute name="date" type="xsd:date" use="required" />
  <xsd:attribute name="amount" type="Currency" use="required"/>
 </xsd:complexType>
</xsd:schema>

=== cosimo265598/distributedprogramming_2/xml_file/Lab1/accounts.xml
<?xml version="1.0"?>
<MultiAccountBank xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" 
    xsd:noNamespaceSchemaLocation="accounts.xsd">

<account number="123456">
  <holder name="Elia" address="Via dei Pioppi, 21" fiscalID="MNSCSM94L13E205Y" />
  <holder name="Francesco" address="Via dei Pioppi, 20" fiscalID="PNSCSM94L13E205Y" />
    <yearOperations year="1999"> 
  	<operation date="1999-12-12" amount="10">
  		<description>Prova acquisto</description>
  	</operation>
  </yearOperations>
  <yearOperations year="2000"> 
  	<operation date="1999-12-12" amount="10">
  		<description>Prova acquisto</description>
  	</operation>
  </yearOperations>
</account>


<account number="123457"> 
  <holder name="Francesco" address="Via dei Pioppi, 20" fiscalID="MNSCSM94L13E205Y" />
    <yearOperations year="1999"> 
  	<operation date="1999-12-12" amount="10">
  		<description>Prova acquisto</description>
  	</operation>
  </yearOperations>
  <yearOperations year="2000"> 
  	<operation date="1999-12-12" amount="10">
  		<description>Prova acquisto</description>
  	</operation>
  </yearOperations>
</account>


<account number="123458">
  <holder name="Umberto" address="Via dei Pioppi, 20" fiscalID="MNSCSM94L13E205Y" />
  <yearOperations year="1999"> 
  	<operation date="1999-12-12" amount="10">
  		<description>Prova acquisto</description>
  	</operation>
  </yearOperations>
  <yearOperations year="2000"> 
  	<operation date="1999-12-12" amount="10">
  		<description>Prova acquisto</description>
  	</operation>
  </yearOperations>
</account>


</MultiAccountBank>
