=== cosimo265598/distributedprogramming_2/xml_file/Lab1/biblio_3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	    targetNamespace="http://pad.polito.it/dp2/biblio"
	    xmlns:tns="http://pad.polito.it/dp2/biblio"
>
    
    <element name="biblio">
		<complexType>
			<sequence>
				<element name="article" type="tns:ArticleType" maxOccurs="unbounded" minOccurs="0">				</element>
				<element name="book" type="tns:BookType" maxOccurs="unbounded" minOccurs="0">				</element>
				<element name="journal" type="tns:JournalType" maxOccurs="unbounded" minOccurs="0">
					<unique name="issueUniqueness">
						<selector xpath="issue" />
						<field xpath="@year" />
						<field xpath="@number" />
					</unique>	
				</element>
				
				<element name="bookchapter" type="tns:new_chapterType2" minOccurs="0" maxOccurs="unbounded"/>
				
			</sequence>
		</complexType>
		<key name="journalKey">
			<selector xpath="journal" />
			<field xpath="@ISSN" />
		</key>
		<keyref name="journalReference" refer="tns:journalKey">
			<selector xpath="article" />
			<field xpath="@journal" />
		</keyref>
		<key name="issueKey">
			<selector xpath="journal/issue" />
			<field xpath="@id"/>
		</key>
		<keyref name="issueReference" refer="tns:issueKey">
			<selector xpath="article" />
			<field xpath="@issue" />
		</keyref>
		<key name="itemKey_moredirection">
			<selector xpath="article | book"/>   <!-- Operator union for xpath -->
			<field xpath="@id"/>
		</key>
		<keyref name="Reference" refer="tns:itemKey_moredirection">
			<selector xpath="article/citedBy | book/citedBy" />
			<field xpath="." />
		</keyref>
		<unique name="bookUniqueness">
			<selector xpath="book" />
			<field xpath="@ISBN" />
		</unique>
		<!-- PUNTO 1 ESERCIZIO 3 -->
		<unique name="journalTitle">
			<selector xpath="journal"/>
			<field xpath="title"></field>
		</unique>
		<!-- AGGIUNTA RISPETTO ALLA VERSIONE PRECEDNTE -->		
		<keyref name="isbnToKey" refer="tns:bookUniqueness">  <!-- Posso puntare direttamente BookUniqueness -->
			<selector xpath="bookchapter"/>
			<field xpath="@chapterOnBook"/>
		</keyref>
		
		<unique name="uniqueChapter1">
			<selector xpath="bookchapter"></selector>
			<field xpath="@chapterOnBook"></field>
			<field xpath="@num_cap"></field>
		</unique>
		
		<unique name="uniqueChapter2">
			<selector xpath="bookchapter"></selector>
			<field xpath="@chapterOnBook"></field>
			<field xpath="title"></field>
		</unique>
		


	</element>

	<complexType name="BiblioItemType">
		<sequence>
			<element name="author" type="string" maxOccurs="unbounded" minOccurs="1"/>
			<element name="title" type="string"/>
			<element name="subtitle" type="string" minOccurs="0"/>
			<element name="citedBy" type="integer" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="id" type="integer"/>
	</complexType>
	
	<complexType name="chapterType">
		<sequence>
			<element name="titleChapter" type="string" />
		</sequence>
			<attribute name="chapterOnBook" type="tns:ISBNCode" use="required" />
			<attribute name="num_cap" type="positiveInteger" use="required" />
	</complexType>
	
	<complexType name="new_chapterType">
		<complexContent>
			<extension base="tns:BiblioItemType">
				<attribute name="chapterOnBook" type="tns:ISBNCode" use="required" />
				<attribute name="num_cap" type="positiveInteger" use="required" />
			</extension>
			
		</complexContent>
	</complexType>
	<complexType name="new_chapterType2">
		<complexContent>
			<restriction base="tns:new_chapterType">
					<sequence>
						<element name="author" type="string" maxOccurs="unbounded" minOccurs="1"/>
						<element name="title" type="string"/>
					</sequence>
				<attribute name="chapterOnBook" type="tns:ISBNCode" use="required" />
				<attribute name="num_cap" type="positiveInteger" use="required" />
			</restriction>
			
		</complexContent>
	</complexType>
	
	
	<complexType name="ArticleType">
	<complexContent>
		<extension base="tns:BiblioItemType">     <!-- Estenzione di un tipo base complesso itemBiblio -->
			<attribute name="journal" type="tns:ISSNCode" use="required"/>
			<attribute name="issue" type="integer" use="required"/>
		</extension>
	</complexContent>
		
	</complexType>
	
	<complexType name="BookType">
		<complexContent>
			<extension base="tns:BiblioItemType">
				<sequence>
					<element name="publisher" type="string"/>
				</sequence>
				<attribute name="ISBN" type="tns:ISBNCode" use="required"/>
				<attribute name="year" type="gYear" use="required"/>
			</extension>		
		</complexContent>
	</complexType>
	
	<complexType name="JournalType">
		<sequence>
			<element name="title" type="string"></element>
			<element name="publisher" type="string"></element>
			<element name="issue" maxOccurs="unbounded" minOccurs="0">
				<complexType>
					<attribute name="id" type="integer" use="required"/>
					<attribute name="year" type="gYear" use="required"/>
					<attribute name="number" type="positiveInteger" use="required"/>					
				</complexType>
			</element>
		</sequence>
		<attribute name="ISSN" type="tns:ISSNCode" use="required"/>
	</complexType>
		
	<!-- ISBN code is a 10 or 13 digit code. If it is 10 digits long the last digit may be a X -->  
	<simpleType name="ISBNCode"> 
	  <restriction base="string"> 
	   <pattern value="[0-9]{13}"/>
	   <pattern value="[0-9]{9}([0-9]|X)"/>
	  </restriction> 
	</simpleType>
	
	<!-- ISSN code is a 8 digit code with a dash dividing the two groups
	     of 4 digits and the last digit may be a X -->  
	<simpleType name="ISSNCode"> 
	  <restriction base="string"> 
	   <pattern value="[0-9]{4}-[0-9]{3}([0-9]|X)"/>
	  </restriction> 
	</simpleType>
</schema>

=== cosimo265598/distributedprogramming_2/xml_file/Lab1/biblio_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:biblio xmlns:tns="http://pad.polito.it/dp2/biblio"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://pad.polito.it/dp2/biblio biblio_3.xsd ">
            
            
                        
  <article journal="0141-9331" issue="0" id="0">
    <author>T. Sauter</author>
    <author>C. Schwaiger</author>
    <title>Achievement of secure Internet access to fieldbus systems</title>
    <citedBy>1</citedBy>
    <citedBy>2</citedBy>
  </article>
  <article journal="1551-3203" issue="7" id="1">
    <author>M. Cheminod</author>
    <author>A. Pironti</author>
    <author>R. Sisto</author>
    <title>Formal Vulnerability Analysis of a Security System for Remote Fieldbus Access</title>
    <citedBy>2</citedBy>
  </article>
  <book ISBN="0131411551" year="2004" id="2">
    <author>W. Richard Stevens</author>
    <author>Bill Fenner</author>
    <author>Andrew M. Rudoff</author>
    <title>Unix network programming</title>
    <subtitle>Volume 1: The sockets networking API</subtitle>
    <citedBy>2</citedBy>
    <citedBy>3</citedBy>
    <citedBy>0</citedBy>
    <publisher>Addison Wesley</publisher>
  </book>
  
  <book ISBN="0131411552" year="2004" id="3">
    <author>W. Richard Stevens</author>
    <author>Bill Fenner</author>
    <author>Andrew M. Rudoff</author>
    <title>Unix network programming</title>
    <subtitle>Volume 1: The sockets networking API</subtitle>
    <citedBy>1</citedBy>
    <citedBy>0</citedBy>
    <citedBy>3</citedBy>
    <publisher>Addison Wesley</publisher>
  </book>
  
    
  <!-- JOURNAL PART THAT DOES NOT CHANGE -->
   
  <journal ISSN="0141-9331">
  	<title>Microprocessors and Microsystems</title>
  	<publisher>Elsevier</publisher>
    <issue id="0" number="7" year="2002"/>
  </journal>
  <journal ISSN="1551-3203">
    <title>IEEE Transactions on Industrial Informatics</title>
    <publisher>IEEE</publisher>
    <issue id="1" number="1" year="2011"/>
    <issue id="2" number="2" year="2011"/>
    <issue id="3" number="3" year="2011"/>
    <issue id="4" number="4" year="2011"/>
    <issue id="5" number="5" year="2011"/>
    <issue id="6" number="6" year="2011"/>
    <issue id="7" number="7" year="2011"/>
    <issue id="8" number="8" year="2011"/>
    <issue id="9" number="9" year="2011"/>
    <issue id="10" number="10" year="2011"/>
    <issue id="11" number="11" year="2011"/>
    <issue id="12" number="12" year="2011"/>
  </journal>
  <journal ISSN="0141-9332">
  	<title>Microprocessors and Microsystems plus</title>
  	<publisher>Elsevier</publisher>
    <issue id="13" number="1" year="2002"/>
  </journal>
  
  
     
   <!--  REFERING TO THE firt book -->
   <bookchapter num_cap="1" chapterOnBook="0131411551">
   	<author>Bill Fenner</author>
   	<title>Prima parte</title>
  </bookchapter>
  
  <bookchapter num_cap="5" chapterOnBook="0131411551">
   	<author>Bill Fenner</author>
   	<title>Quinta parte</title>
  </bookchapter>
    
    
  <bookchapter num_cap="1" chapterOnBook="0131411552">
   	<author>Bill Fenner</author>
   	<title>Prima parte</title>
  </bookchapter>
  
  <bookchapter num_cap="2" chapterOnBook="0131411552">
   	<author>Bill Fenner</author>
   	<title>Seconda parte</title>
  </bookchapter>

  
  
  
</tns:biblio>
